name = "animegarden"
compatibility_date = "2023-03-22"

main = "src/index.ts"

kv_namespaces = [
  { binding = "animegarden", id = "d0bb91899b22468db08020b251d3cef4", preview_id = "0bcc680779d340dfb80a3512a89cb533" },
]

[triggers]
crons = ["*/5 * * * *"]
